# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, verbose_name='URL')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='C:\\Users\\Sergey\\PycharmProjects\\MULTYDOM\\static/other')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.Category', verbose_name='Входит в группу')),
            ],
            options={
                'verbose_name': 'Товарная группа',
                'db_table': 'category',
                'verbose_name_plural': 'Товарные группы',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, verbose_name='URL')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='C:\\Users\\Sergey\\PycharmProjects\\MULTYDOM\\static/other')),
                ('manufacturerText', models.TextField(blank=True, max_length=1000, verbose_name='Описание производителя')),
                ('manufacturerCountry', models.CharField(blank=True, max_length=50, verbose_name='Страна производства')),
            ],
            options={
                'verbose_name': 'Производитель',
                'db_table': 'manufacturer',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=100, unique=True, verbose_name='Название товара')),
                ('productSlug', models.CharField(max_length=100, verbose_name='URL')),
                ('productDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('productDateChange', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('productStartPrice', models.IntegerField(default=0, verbose_name='Начальная цена')),
                ('productStartPriceInDollars', models.BooleanField(default=False, verbose_name='Цена в долларах')),
                ('productCurrentPrice', models.IntegerField(default=0, verbose_name='Текущая цена')),
                ('productPresence', models.BooleanField(default=True, verbose_name='В наличии')),
                ('productForOrder', models.BooleanField(default=False, verbose_name='Под заказ')),
                ('productSize', models.CharField(blank=True, max_length=100, verbose_name='Размер(без слова "размер")')),
                ('productPhoto_original', imagekit.models.fields.ProcessedImageField(upload_to='C:\\Users\\Sergey\\PycharmProjects\\MULTYDOM\\static/products/', verbose_name='Фото товара формат (выс4*шир3)')),
                ('productPhoto_medium', models.CharField(blank=True, editable=False, max_length=255)),
                ('productPhoto_thumb', models.CharField(blank=True, editable=False, max_length=255)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория товара')),
                ('productManufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'db_table': 'product',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
