# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160113_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productText',
            new_name='product_text',
        ),
    ]
